FROM amazoncorretto:17-alpine-jdk

WORKDIR /app
# `.jar` 파일명은 프로젝트에 맞게 수정
COPY ./build/libs/demo-0.0.1-SNAPSHOT.jar /app/app.jar

ENV TZ=Asia/Seoul

CMD ["java", "-jar", "-Dspring.profiles.active=dev", "app.jar"]
