version: '3.8'

services:
  mysql:
    image: mysql:8.3.0
    container_name: mysql8
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: example
      MYSQL_PASSWORD: example
      MYSQL_DATABASE: example
      MYSQL_ROOT_PASSWORD: example
      TZ: 'Asia/Seoul'
    volumes:
      - mysqldb:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis:7.2.4-alpine
    container_name: redis7
    command: redis-server --port 6379
    restart: always
    hostname: root
    labels:
      - "mode:standalone"
    ports:
      - "6379:6379"

volumes:
  mysqldb:
